// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3KUmjtNHqtfHkfGvEhKPE0KNrca6y5R8',
    appId: '1:1000132971352:web:cb230f32fac4025190f32d',
    messagingSenderId: '1000132971352',
    projectId: 'ai-photo-cleaner-b945e',
    authDomain: 'ai-photo-cleaner-b945e.firebaseapp.com',
    storageBucket: 'ai-photo-cleaner-b945e.firebasestorage.app',
    measurementId: 'G-9P2CFL8G1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKSF0MUI95y4-uX4NwHgqMsTdEDYbtX_A',
    appId: '1:1000132971352:android:a0d987c76c3c016b90f32d',
    messagingSenderId: '1000132971352',
    projectId: 'ai-photo-cleaner-b945e',
    storageBucket: 'ai-photo-cleaner-b945e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRIBW-1NnapcdeCImFqEf3mlFSLFaPS4',
    appId: '1:1000132971352:ios:1f2574263658b20890f32d',
    messagingSenderId: '1000132971352',
    projectId: 'ai-photo-cleaner-b945e',
    storageBucket: 'ai-photo-cleaner-b945e.firebasestorage.app',
    iosBundleId: 'com.felix.aiPhotoCleaner',
  );
}
